C-sharp/HealthObservations/HealthObservations/Models/Patient.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HealthObservations.Models
{
    /**
     * Patient data 
     * */
    public class Patient
    {
        public virtual int Id { get; set; }
        public virtual string Lastname { get; set; }
        public virtual string Firstname { get; set; }
        public virtual ICollection<Measurement> MeasurementList { get; set; }
        //Convenience - perhaps put in separate ViewModel or decorator object?
        public virtual IEnumerable<DateTime> ObservationTimes()
        {
            var query = from measurement in MeasurementList
                        where measurement.PatientId == Id
                        select measurement.ObservationTime;
            List<DateTime> times = query.ToList();
            return times;
        }
        //Convenience - perhaps put in ViewModel or decorator object?
        public virtual IEnumerable<int> Observations()
        {
            var query = from measurement in MeasurementList
                        where measurement.PatientId == Id
                        select measurement.Observation;
            List<int> times = query.ToList();
            return times;
        }
    }
}

C-sharp/HealthObservations/HealthObservations/Controllers/ObservationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HealthObservations.Models;

namespace HealthObservations.Controllers
{
    public class ObservationsController : Controller
    {
        private PatientsDBContext db = new PatientsDBContext();

        //
        // GET: /Observations/

        public ActionResult Index()
        {
            return View(db.Measurements.ToList());
        }

        //
        // GET: /Observations/Details/5

        public ActionResult Details(int id = 0)
        {
            Measurement measurement = db.Measurements.Find(id);
            if (measurement == null)
            {
                return HttpNotFound();
            }
            return View(measurement);
        }

        //
        // GET: /Observations/Create

        public ActionResult Create(int id = 0)
        {
            //create list of patients and associated ID's
            //TODO There are better ways to do this...
            List<Patient> pats = new List<Patient>();
            foreach (Patient p in db.Patients)
            {
                pats.Add(p);
            }
            ViewData["patients"] = pats;
            return View();
        }

        //
        // POST: /Observations/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Measurement measurement)
        {
            if (ModelState.IsValid)
            {
                db.Measurements.Add(measurement);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(measurement);
        }

        //
        // GET: /Observations/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Measurement measurement = db.Measurements.Find(id);
            if (measurement == null)
            {
                return HttpNotFound();
            }
            ViewBag.PatientList = new SelectList(db.Patients, "Id", "Lastname");
            return View(measurement);
        }

        //
        // POST: /Observations/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Measurement measurement)
        {
            if (ModelState.IsValid)
            {
                db.Entry(measurement).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(measurement);
        }

        //
        // GET: /Observations/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Measurement measurement = db.Measurements.Find(id);
            if (measurement == null)
            {
                return HttpNotFound();
            }
            return View(measurement);
        }

        //
        // POST: /Observations/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Measurement measurement = db.Measurements.Find(id);
            db.Measurements.Remove(measurement);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

C-sharp/HealthObservations/HealthObservations/Controllers/PatientController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HealthObservations.Models;

namespace HealthObservations.Controllers
{
    public class PatientController : Controller
    {
        private PatientsDBContext db = new PatientsDBContext();
        
        
        // GET: /Patient/

        public ActionResult Index()
        {
            ViewBag.Patients = db.Patients.ToList();
            ViewBag.Measurements = db.Measurements.ToList();
            return View(db.Patients);
        }

        //
        // GET: /Patient/Details/5

        public ActionResult Details(int id = 0)
        {
            Patient patient = db.Patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        //
        // GET: /Patient/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Patient/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Patient patient)
        {
            if (ModelState.IsValid)
            {
                db.Patients.Add(patient);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(patient);
        }

        //
        // GET: /Patient/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Patient patient = db.Patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        //
        // POST: /Patient/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Patient patient)
        {
            if (ModelState.IsValid)
            {
                db.Entry(patient).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(patient);
        }

        //
        // GET: /Patient/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Patient patient = db.Patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        //
        // POST: /Patient/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Patient patient = db.Patients.Find(id);
            db.Patients.Remove(patient);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

C-sharp/HealthObservations/HealthObservations/Views/Patient/Create.cshtml
@model HealthObservations.Models.Patient

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Patient</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Lastname)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Lastname)
            @Html.ValidationMessageFor(model => model.Lastname)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Firstname)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Firstname)
            @Html.ValidationMessageFor(model => model.Firstname)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

C-sharp/HealthObservations/HealthObservations/Views/Patient/Delete.cshtml
@model HealthObservations.Models.Patient

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Patient</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Lastname)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Lastname)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Firstname)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Firstname)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

C-sharp/HealthObservations/HealthObservations/Views/Patient/Details.cshtml
@model HealthObservations.Models.Patient
@using HealthObservations.App_Code;

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Patient</legend>

    <div>
        <h2>@Html.DisplayFor(model => model.Firstname) @Html.DisplayFor(model => model.Lastname)</h2>
    </div>


    @foreach (HealthObservations.Models.Measurement measure in Model.MeasurementList)
    {
        <div>@measure.ObservationTime @measure.Observation kg Note:    @measure.Notes</div>   
    }
</fieldset>
@{ 
     if (Model.MeasurementList.Count > 0)
    {
        HealthObservations.App_Code.Grapher graph = new Grapher(Model.ObservationTimes(), Model.Observations());
        graph.Height = 600;
        graph.Width = 600;
        string imgname = @Url.Content(graph.FilePathName);
    <img src= '@(imgname)'  class="chart" title="Trendline of observations" />
    } 
}
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
    </p>

C-sharp/HealthObservations/HealthObservations/Views/Patient/Edit.cshtml
@model HealthObservations.Models.Patient

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Patient</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Lastname)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Lastname)
            @Html.ValidationMessageFor(model => model.Lastname)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Firstname)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Firstname)
            @Html.ValidationMessageFor(model => model.Firstname)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

C-sharp/HealthObservations/HealthObservations/Views/Patient/Index.cshtml
@model IEnumerable<HealthObservations.Models.Patient>
@using HealthObservations.App_Code;

@{
    ViewBag.Title = "Patients";
}
<h2>Here are the patients and observations</h2>
<table>
    <tr>
        <th>
            @* These should be localized using resource files *@
            Patient Name
        </th>
        <th>    
        </th>
        <th>Measurements</th>
        <th>Actions</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr class="patientRow">
            <td class="patientName">
                @Html.DisplayFor(modelItem => item.Lastname) ,&nbsp;  @Html.DisplayFor(modelItem => item.Firstname)
            </td>
            <td>
                
            </td>
            <td>
                @{ if (item.MeasurementList.Count > 0)
                   {
                       List<DateTime> range = item.ObservationTimes().ToList();
                       List<int> measurements = item.Observations().ToList();
                       HealthObservations.App_Code.Grapher graph = new Grapher(range, measurements);
                       graph.Height = 300;
                       graph.Width = 300;
                       string imgname = @Url.Content(graph.FilePathName);
                    <a href='@Url.Action("Create","Observations",new {Id= item.Id})' > <img src= '@(imgname)'  class="chart" title="Trendline of observations Click for add"/></a>
                   } 
                }
            </td>

            <td>
                <a href='@Url.Action("Edit", "Patient", new { Id = item.Id })'>
                    <img src='@Url.Content("~/Images/Pencil.png")' width="20" height="20" alt="Edit Patient Demographics" title="Edit Patient Demographics only"/></a> 
                <a href='@Url.Action("Details", "Patient", new { Id = item.Id })' >
                    <img src='@Url.Content("~/Images/Document_generic.png")' width="20" height="20" alt="View Patient Details" title="View Full Patient Details including larger graph"/></a>
                <a href='@Url.Action("Delete", "Patient", new { Id = item.Id })'>   
                    <img src='@Url.Content("~/Images/DeleteRed_small.png")' width="20" height="20" alt="Delete Patient and Details" title="Delete Patient and Details"/>
                </a>
                <!--            @Html.ActionLink("Details", "Details", new { id = item.Id }) | 
                @Html.ActionLink("Delete", "Delete", new { id = item.Id }) -->
            </td>
        </tr>
    }

</table>
<p>
    @Html.ActionLink("Add New Patient", "Create")

</p>
<p>@Html.ActionLink("Add Measurements", "Create","Observations")
</p>